language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-francis-craft' ]; then cd .. && eval "mv $currentfolder generator-francis-craft" && cd generator-francis-craft; fi

