/*
 Copyright (c) 2014, Pixel & Tonic, Inc.
 @license   http://buildwithcraft.com/license Craft License Agreement
 @see       http://buildwithcraft.com
 @package   craft.app.resources
*/
(function(c){Craft.RichTextInput=Garnish.Base.extend({id:null,sectionSources:null,elementLocale:null,redactorConfig:null,$textarea:null,redactor:null,init:function(a,b,f,d,e){this.id=a;this.sectionSources=b;this.elementLocale=f;this.redactorConfig=d;this.redactorConfig.lang=e;this.redactorConfig.direction=Craft.orientation;var g=this,h=d.initCallback;this.redactorConfig.initCallback=function(a,b){g.redactor=this;g.onRedactorInit();return c.isFunction(h)?h.call(this,a,b):b};this.$textarea=c("#"+this.id);
this.initRedactor();"undefined"!=typeof Craft.livePreview&&(Craft.livePreview.on("beforeEnter beforeExit",c.proxy(function(){this.redactor.destroy()},this)),Craft.livePreview.on("enter slideOut",c.proxy(function(){this.initRedactor()},this)))},initRedactor:function(){this.$textarea.redactor(this.redactorConfig);this.redactor=this.$textarea.data("redactor")},onRedactorInit:function(){this.replaceRedactorButton("image",Craft.t("Insert image"),null,{from_web:{title:Craft.t("Insert URL"),func:"imageShow"},
from_assets:{title:Craft.t("Choose image"),callback:c.proxy(function(){this.redactor.selectionSave();var a=this.redactor;"undefined"==typeof this.assetSelectionModal?this.assetSelectionModal=Craft.createElementSelectorModal("Asset",{storageKey:"RichTextFieldType.ChooseImage",multiSelect:!0,criteria:{locale:this.elementLocale,kind:"image"},onSelect:c.proxy(function(b,f){if(b.length){a.selectionRestore();for(var d=0;d<b.length;d++){var e=b[d],e=e.url+"#asset:"+e.id;f&&(e+=":"+f);a.insertNode(c('<img src="'+
e+'" />')[0]);a.sync()}a.observeImages();a.dropdownHideAll()}},this),closeOtherModals:!1,canSelectImageTransforms:!0}):this.assetSelectionModal.show()},this)}});this.replaceRedactorButton("link",Craft.t("Link"),null,{link_entry:{title:Craft.t("Link to an entry"),callback:c.proxy(function(){this.redactor.selectionSave();var a=this.redactor;"undefined"==typeof this.entrySelectionModal?this.entrySelectionModal=Craft.createElementSelectorModal("Entry",{storageKey:"RichTextFieldType.LinkToEntry",sources:this.sectionSources,
criteria:{locale:this.elementLocale},onSelect:function(b){if(b.length){a.selectionRestore();b=b[0];var f=b.url+"#entry:"+b.id,d=a.getSelectionText();a.insertNode(c('<a href="'+f+'">'+(0<d.length?d:b.label)+"</a>")[0]);a.sync()}a.dropdownHideAll()},closeOtherModals:!1}):this.entrySelectionModal.show()},this)},link_asset:{title:Craft.t("Link to an asset"),callback:c.proxy(function(){this.redactor.selectionSave();var a=this.redactor;"undefined"==typeof this.assetLinkSelectionModal?this.assetLinkSelectionModal=
Craft.createElementSelectorModal("Asset",{storageKey:"RichTextFieldType.LinkToAsset",criteria:{locale:this.elementLocale},onSelect:function(b){if(b.length){a.selectionRestore();b=b[0];var f=b.url+"#asset:"+b.id,d=a.getSelectionText();a.insertNode(c('<a href="'+f+'">'+(0<d.length?d:b.label)+"</a>")[0]);a.sync()}a.dropdownHideAll()},closeOtherModals:!1,canSelectImageTransforms:!0}):this.assetLinkSelectionModal.show()},this)},link:{title:Craft.t("Insert link"),func:"linkShow"},unlink:{title:Craft.t("Unlink"),
exec:"unlink"}});if("undefined"!=typeof this.redactor.fullscreen&&"function"==typeof this.redactor.toggleFullscreen)Craft.cp.on("beforeSaveShortcut",c.proxy(function(){this.redactor.fullscreen&&this.redactor.toggleFullscreen()},this))},replaceRedactorButton:function(a,b,c,d){if(this.redactor.buttonGet(a).length){var e=a+"_placeholder";this.redactor.buttonAddAfter(a,e);this.redactor.buttonRemove(a);this.redactor.buttonAddAfter(e,a,b,c,d);this.redactor.buttonRemove(e)}}})})(jQuery);

//# sourceMappingURL=RichTextInput.min.map
